WebMVCDemo/MyBookStoreApp.Web/ViewModels/BookViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MyBookStoreApp.MyBookStoreApp.Domain.Models;
using System.ComponentModel.DataAnnotations;

namespace MyBookStoreApp.MyBookStoreApp.Web.ViewModels
{
    public class BookViewModel
    {
        public Guid BookId { get; set; }
        [Required]
        public string Title { get; set; } = string.Empty;

        [Required]
        public Guid AuthorId { get; set; }

        [Required]
        public Guid GenreId { get; set; }

        [Required]
        [Range(0, double.MaxValue)]
        public decimal Price { get; set; }

        [Required]
        public DateTime PublicationDate { get; set; }
        public string AuthorName { get; set; }
        public string BookGenre { get; set; }
        public SelectList Authors { get;set; }
        public SelectList Genres { get;set; }
    }

}

WebMVCDemo/MyBookStoreApp.Web/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using MyBookStoreApp.MyBookStoreApp.Domain.Models;
using MyBookStoreApp.MyBookStoreApp.Web.ViewModels;
using MyBookStoreApp.MyBookStoreApp.Domain.Services;
using MyBookStoreApp.MyBookStoreApp.Domain.Repositories;

namespace MyBookStoreApp.MyBookStoreApp.Web.Controllers
{
    public class AuthorController : Controller
    {
        private readonly AuthorService _authorService;

        public AuthorController(AuthorService authorService)
        {
            _authorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            var allAuthors = new List<AuthorViewModel>();
            var authors = await _authorService.GetAllAuthors();
            foreach (var author in authors)
            {
                var authorViewModel = new AuthorViewModel();
                authorViewModel.AuthorId = author.AuthorId;
                authorViewModel.FirstName = author.FirstName;
                authorViewModel.LastName = author.LastName;
                authorViewModel.Email = author.Email;
                allAuthors.Add(authorViewModel);
            }
            return View(allAuthors);
        }

        // GET: /Author/Create
        public IActionResult Create()
        {
            var viewModel = new AuthorViewModel();
            return View(viewModel);
        }

        // POST: /Author/Create
        [HttpPost]
        public async Task<IActionResult> Create(AuthorViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var author = new Author
                    {
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        Email = viewModel.Email,
                        AuthorId = Guid.NewGuid(),
                    };

                    await _authorService.CreateAuthor(author);
                    ViewBag.SuccessMessage = $"Author {viewModel.FirstName} {viewModel.LastName} added successfully!";
                    //ViewBag.FailureMessage = "";
                    viewModel = null;
                }
                else
                {
                    ViewBag.FailureMessage = "The data you filled in is invalid. Please try again!";
                }
            }
            catch (Exception)
            {
                ViewBag.FailureMessage = "There was some error adding this author. Please try again!";
                //ViewBag.SuccessMessage = "";
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Update(string id)
        {
            var author = await _authorService.GetAuthorById(Guid.Parse(id));
            var authorViewModel = new AuthorViewModel
            {
                FirstName = author.FirstName,
                LastName = author.LastName,
                Email = author.Email,
                AuthorId = author.AuthorId
            };
            return View(authorViewModel);
        }

        [HttpPatch]
        public async Task<IActionResult> Update(AuthorViewModel authorViewModel)
        {
            var author = await _authorService.GetAuthorById(authorViewModel.AuthorId);
            
            // Map the properties from the view model to the actual author model
            author.FirstName = authorViewModel.FirstName;
            author.LastName = authorViewModel.LastName;
            author.Email = authorViewModel.Email;
            
            await _authorService.UpdateAuthor(author);
            return View(author.AuthorId.ToString());
        }

        
        public async Task<IActionResult> Delete(string id)
        {
            await _authorService.DeleteAuthor(Guid.Parse(id));
            return RedirectToAction("Index");
        }
    }

}

WebMVCDemo/MyBookStoreApp.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using MyBookStoreApp.MyBookStoreApp.Domain.Models;
using MyBookStoreApp.MyBookStoreApp.Domain.Services;
using MyBookStoreApp.MyBookStoreApp.Domain.Repositories;
using MyBookStoreApp.MyBookStoreApp.Web.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace MyBookStoreApp.MyBookStoreApp.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly BookService _bookService;
        private readonly GenreService _genreService;
        private readonly AuthorService _authorService;
        private static SelectList _authors;
        private static SelectList _genres;
        //private Dictionary<Guid, string> _authors = new Dictionary<Guid, string>();
        //private Dictionary<Guid, string> _genres = new Dictionary<Guid, string>();
        public BookController(BookService bookService, AuthorService authorService, GenreService genreService)
        {
            _bookService = bookService;
            _authorService = authorService;
            _genreService = genreService;
        }

        private async Task GetAuthorsAndGenres()
        {
            var authors = await _authorService.GetAllAuthors();
            _authors = new SelectList(authors.Select(kv => new SelectListItem { Value = kv.AuthorId.ToString(), Text = $"{kv.FirstName} {kv.LastName}" }).ToList(), "Value", "Text");
            var genres = await _genreService.GetAllGenres();
            _genres = new SelectList(genres.Select(kv => new SelectListItem { Value = kv.GenreId.ToString(), Text = kv.Name }).ToList(), "Value", "Text");
        }

        public async Task<IActionResult> Index()
        {
            await GetAuthorsAndGenres();
            var bookViewModel = new List<BookViewModel>();
            var books = _bookService.GetAllBooks();
            foreach (var book in books.Result)
            {
                bookViewModel.Add(
                    new BookViewModel
                    {
                        Title = book.Title,
                        AuthorId = book.AuthorId,
                        BookId = book.BookId,
                        GenreId = book.GenreId,
                        Price = book.Price,
                        PublicationDate = book.PublicationDate.DateTime,
                        AuthorName = book.Author.FirstName + " " + book.Author.LastName,
                        BookGenre= book.Genre.Name,
                        Authors = _authors,
                        Genres = _genres
                    });
            }
            return View(bookViewModel);
        }

        //// GET: /Book/Create
        public async Task<IActionResult> Create()
        {
            await GetAuthorsAndGenres();
            // Create an instance of BookViewModel
            var viewModel = new BookViewModel
            {
                Authors = _authors,
                Genres = _genres
            };
            return View(viewModel);
        }

        // POST: /Book/Create
        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel viewModel)
        {
            ModelState.Remove("Authors");
            ModelState.Remove("Genres");
            ModelState.Remove("AuthorName");
            ModelState.Remove("BookGenre");
            if (ModelState.IsValid)
            {
                // Map the ViewModel data to the Model
                var book = new Book
                {
                    BookId = Guid.NewGuid(),
                    Title = viewModel.Title,
                    AuthorId = viewModel.AuthorId,
                    GenreId = viewModel.GenreId,
                    Price = viewModel.Price,
                    PublicationDate = new DateTimeOffset(viewModel.PublicationDate,TimeSpan.Zero)
                };

                await _bookService.CreateBook(book);
            }
            viewModel.Authors = _authors;   
            viewModel.Genres = _genres; 
            return View(viewModel);
        }

        // GET: /Book/Update
        public async Task<IActionResult> Update(string id)
        {
            var book = await _bookService.GetBookById(Guid.Parse(id));
            var viewModel = new BookViewModel
            {
                BookId = book.BookId,
                Title = book.Title,
                AuthorId = book.AuthorId,
                GenreId = book.GenreId,
                Price = book.Price,
                PublicationDate = book.PublicationDate.DateTime,
                Authors = _authors,
                Genres = _genres
            };

            return View(viewModel);
        }
        [HttpPatch]
        public async Task<IActionResult> Update(BookViewModel viewModel)
        {
            // Map the ViewModel data to the Model
            var book = new Book
            {
                BookId = viewModel.BookId,
                Title = viewModel.Title,
                AuthorId = viewModel.AuthorId,
                GenreId = viewModel.GenreId,
                Price = viewModel.Price,
                PublicationDate = new DateTimeOffset(viewModel.PublicationDate,TimeSpan.Zero)
                // Assuming current date
            };

            await _bookService.UpdateBook(book);
            return View(viewModel);
        }

   
        public async Task<IActionResult> Delete(string id)
        {
            await _bookService.DeleteBook(Guid.Parse(id));
            return RedirectToAction("Index");
        }
    }
}

WebMVCDemo/MyBookStoreApp.Web/Views/Book/Create.cshtml
@using MyBookStoreApp.MyBookStoreApp.Web.ViewModels;
@model MyBookStoreApp.MyBookStoreApp.Web.ViewModels.BookViewModel

<h2 class="card-header">Add Book</h2>
<div class="p-3">
    <form method="post">
        <div class="container">
            <div class="form-group my-5 row">
                <label asp-for="Title" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="Title" class="form-control col" />
                    <span asp-validation-for="Title" class="col  text-danger"></span>
                </div>
            </div>

           @* <div class="form-group my-5 row">
                <label asp-for="GenreId" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="GenreId" class="form-control col" />
                    <span asp-validation-for="GenreId" class="col text-danger"></span>
                </div>
            </div>*@
            <div class="form-group my-5 row">
                <label asp-for="GenreId" class="form-label col-md-2">Genre</label>
                <div class="col-md-10 row">
                    <select asp-for="GenreId" asp-items="Model.Genres" class="form-select col">
                        <option value="">Select an option</option>
                    </select>
                    <span asp-validation-for="GenreId" class="col text-danger"></span>
                </div>
            </div>
            @*<div class="form-group my-5 row">
                <label asp-for="AuthorId" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="AuthorId" class="form-control col" />
                    <span asp-validation-for="AuthorId" class="col text-danger"></span>
                </div>
            </div>*@
            <div class="form-group my-5 row">
                <label asp-for="AuthorId" class="form-label col-md-2">Author</label>
                <div class="col-md-10 row">
                    <select asp-for="AuthorId" asp-items="Model.Authors" class="form-select col">
                        <option value="">Select an option</option>
                    </select>
                    <span asp-validation-for="AuthorId" class="col text-danger"></span>
                </div>
            </div>
            <div class="form-group my-5 row">
                <label asp-for="PublicationDate" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="PublicationDate" class="form-control col" />
                    <span asp-validation-for="PublicationDate" class="col text-danger"></span>
                </div>
            </div>
            <div class="form-group my-5 row">
                <label asp-for="Price" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="Price" class="form-control col" />
                    <span asp-validation-for="Price" class="col text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="offset-md-2 col-md-4">
                    <button type="submit" class="btn btn-primary">Add</button>
                    <button type="reset" class="btn btn-danger" onclick="resetValidation()">Reset</button>
                </div>
            </div>
            <!-- JavaScript code -->
            <script>
                function resetValidation() {
                    // Clear all validation messages
                    var validationElements = document.getElementsByClassName("text-danger");
                    for (var i = 0; i < validationElements.length; i++) {
                        validationElements[i].textContent = "";
                    }
                }
            </script>
        </div>
    </form>


    <div class="modal-dialog container">
        @if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
        {
            @await Html.PartialAsync("_Alert", new AlertViewModel {
        IsSuccess = true,
        Message = ViewBag.SuccessMessage
        })
        }

        @if (!string.IsNullOrEmpty(ViewBag.FailureMessage))
        {
            @await Html.PartialAsync("_Alert", new AlertViewModel {
        IsSuccess = false,
        Message = ViewBag.FailureMessage
        })
        }
    </div>

</div>

WebMVCDemo/MyBookStoreApp.Web/Views/Book/Index.cshtml
@using MyBookStoreApp.MyBookStoreApp.Web.ViewModels
@model List<BookViewModel>

@{
    ViewBag.Title = "Books";
}

<div class="card px-2 border-bottom-1 bg-light container">
    <div class="row">
        <h3 class="col-4">All Books</h3>
        <div class="col-4">
            <input type="text" class="form-control" />
        </div>
        <div class="col-1">
            <input type="button" class="btn btn-primary" value="Search" />
        </div>
        <div class="col-3">
            <a href="@Url.Action("Create", "Book")" class="btn btn-success">+ Create new</a>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model[0].Title)</th>
                <th>@Html.DisplayNameFor(model => model[0].Price)</th>
                <th>@Html.DisplayNameFor(model => model[0].AuthorName)</th>
                <th>@Html.DisplayNameFor(model => model[0].BookGenre)</th>
                <th>@Html.DisplayNameFor(model => model[0].PublicationDate)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => book.Title)</td>
                    <td>&#8377;@Html.DisplayFor(modelItem => book.Price)</td>
                    <td>@Html.DisplayFor(modelItem => book.AuthorName)</td>
                    <td>@Html.DisplayFor(modelItem => book.BookGenre)</td>
                    <td>@Html.DisplayFor(modelItem => book.PublicationDate)</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="@Url.Action("Update", "Book", new { id = book.BookId })" class="btn btn-primary mx-2">Edit</a>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal_@book.BookId">Delete</button>
                        </div>

                        <!-- Delete Confirmation Modal -->
                        <div class="modal fade" id="deleteConfirmationModal_@book.BookId" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel_@book.BookId" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteConfirmationModalLabel_@book.BookId">Delete Confirmation</h5>
                                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete this author?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary mx-3" data-bs-dismiss="modal">Cancel</button>
                                        <a href="@Url.Action("Delete", "Book", new { id = book.BookId})" class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebMVCDemo/MyBookStoreApp.Web/Views/Book/Update.cshtml
@using MyBookStoreApp.MyBookStoreApp.Web.ViewModels
@model MyBookStoreApp.MyBookStoreApp.Web.ViewModels.BookViewModel

<h2 class="card-header">Edit author details</h2>
<div class="p-3">
    <form method="patch" asp-action="Update" asp-controller="Author">
        <div class="container">
            <input type="hidden" asp-for="BookId" />
            <div class="form-group my-5 row">
                <label asp-for="Title" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="Title" class="form-control col" />
                    <span asp-validation-for="Title" class="col text-danger"></span>
                </div>
            </div>
             
            <div class="form-group my-5 row">
                <label asp-for="GenreId" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="GenreId" class="form-control col" />
                    <span asp-validation-for="GenreId" class="col  text-danger"></span>
                </div>
            </div>

            <div class="form-group my-5 row">
                <label asp-for="Price" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="Price" class="form-control col" />
                    <span asp-validation-for="Price" class="col text-danger"></span>
                </div>
            </div>

            <div class="form-group my-5 row">
                <label asp-for="PublicationDate" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="PublicationDate" class="form-control col" />
                    <span asp-validation-for="PublicationDate" class="col text-danger"></span>
                </div>
            </div>

            <div class="form-group my-5 row">
                <label asp-for="AuthorId" class="form-label col-md-2"></label>
                <div class="col-md-10 row">
                    <input asp-for="AuthorId" class="form-control col" />
                    <span asp-validation-for="AuthorId" class="col text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="offset-md-2 col-md-4">
                    <button type="button" class="btn btn-primary" onclick="updateAuthor()">Update</button>
                    <button type="reset" class="btn btn-danger" onclick="resetValidation()">Reset</button>
                </div>
            </div>
        </div>
    </form>

    <script>
        function updateAuthor() {
            var form = document.querySelector('form');
            var formData = new FormData(form);

            fetch(form.action, {
                method: 'PATCH',
                body: formData
            })
                .then(response => {
                    if (response.ok) {
                        // Handle success
                        console.log('Author details updated successfully.');
                    } else {
                        // Handle failure
                        console.log('Failed to update Author details.');
                    }
                })
                .catch(error => {
                    console.error('An error occurred while updating Author details:', error);
                });
        }

        function resetValidation() {
            // Clear all validation messages
            var validationElements = document.getElementsByClassName("text-danger");
            for (var i = 0; i < validationElements.length; i++) {
                validationElements[i].textContent = "";
            }
        }
    </script>



    <div class="modal-dialog container">
        @if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
        {
            @await Html.PartialAsync("_Alert", new AlertViewModel {
        IsSuccess = true,
        Message = ViewBag.SuccessMessage
        })
        }

        @if (!string.IsNullOrEmpty(ViewBag.FailureMessage))
        {
            @await Html.PartialAsync("_Alert", new AlertViewModel {
        IsSuccess = false,
        Message = ViewBag.FailureMessage
        })
        }
    </div>

</div>